cmake_minimum_required(VERSION 3.20)
project(nwd_consumer LANGUAGES CXX)
find_package(nwd CONFIG REQUIRED)
add_executable(nwd_example main.cpp)
target_link_libraries(nwd_example PRIVATE nwd::reader)
add_executable(nwd_project_example project.cpp)
target_link_libraries(nwd_project_example PRIVATE nwd::reader)
if(MINGW)
 target_link_options(nwd_example PRIVATE -municode -static)
 target_link_options(nwd_project_example PRIVATE -municode -static)
endif()
